#!/bin/sh

# Collects information about RexGen device

set -ue

echo "RexGen CPU = $(cat /home/root/rexusb/var/cputype)"  
echo "RexGen S.N. = $(cat /home/root/rexusb/var/serial)"
echo "RexGen F.W. = $(cat /home/root/rexusb/var/firmware)"
echo "RexGen config = $(cat /home/root/rexusb/var/configuration_name)"
