#!/bin/sh

FILES=$(cat /data/mender/preserved-files | grep -v '#' )
tar -czf /data/mender/preserved-files.tgz $FILES 

/usr/sbin/fw_setenv influx_upgrade 1

/opt/influx/mender_update_start.sh

exit 0
